# Valid Flags of https://s3.amazonaws.com/files.microstrain.com/GQ7+User+Manual/external_content/dcp/Data/0x91/data/0x22.htm

bool tow
bool week_number
bool receiver_id
bool tracking_channel
bool gnss_id
bool satellite_id
bool signal_id
bool signal_strength
bool quality
bool pseudorange
bool carrier_phase
bool doppler
bool range_uncertainty
bool carrier_phase_uncertainty
bool doppler_uncertainty
bool lock_time
